teamG_study/precomi/urls.py
from django.urls import path
from .import views
app_name = 'precomi'
urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
    path('talk/',views.TalkView.as_view(),name="talk"),
    path('notice/',views.NoticeView.as_view(),name="notice"),
    path('diary/',views.DiaryView.as_view(),name="diary"),
    path('diary-detail/<int:pk>/', views.DiaryDetailView.as_view(), name="diary_detail"),
    path('diary-create',views.DiaryCreateView.as_view(),name="diary_create"),
    path('diary-update/<int:pk>/',views.DiaryUpdateView.as_view(),name="diary_update"),
    path('diary-delete/<int:pk>/',views.DiaryDeleteView.as_view(),name="diary_delete"),
    path('inquiry/',views.InquiryView.as_view(),name="inquiry"),
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('profile_update/<int:pk>/', views.ProfileUpdateView.as_view(), name="profile_update"),
    path('profile_create/', views.ProfileCreateView.as_view(), name="profile_create"),
    path('alldiary/',views.AlldiaryView.as_view(),name="alldiary"),
    path('comment/create/<int:pk>',views.CommentView.as_view(),name='comment_create'),

    # path("chat/", views.chat_index, name="chat_index"),
    path('chat/', views.ChatIndexView.as_view(), name='chat_index'),
    path("chat_r/<str:room_name>/", views.chat_room, name="chat_room"),
    path('room/', views.room, name='room'),

]

teamG_study/teamG_study/urls.py
from django.contrib import admin
from django.urls import path,include

# 日記用
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('precomi.urls')),
    path('accounts/',include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teamG_study/precomi/models.py
from django.db import models
from django.utils import timezone
from accounts.models import CustomUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.validators import RegexValidator
import uuid

#プロフィールモデル
#(主キー、名前、生年月日、性別、ユーザパスワード、電話番号、妊娠周期、血液型、症状、ユーザタイプ、病院名、画像5枚、最終ログイン,コメント,緊急連絡先)
class User(models.Model):
    blood = (
        ("A","A型"),
        ("B","B型"),
        ("AB","AB型"),
        ("O","O型")
    )
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    no = models.AutoField(verbose_name='主キー',primary_key=True)
    name = models.CharField(max_length=20,verbose_name='名前',null=False)
    datebirth = models.DateField(verbose_name='生年月日',null=True)
    tel_number_regex = RegexValidator(regex=r'^[0-9]+$', message=("半角数字のみを入力してください"))
    telnum = models.CharField(validators=[tel_number_regex], max_length=12, verbose_name='電話番号', null=False)
    precycle = models.IntegerField(validators=[MinValueValidator(8)],verbose_name='妊娠周期',null=False)
    bloodtype = models.CharField(max_length=2,verbose_name='血液型', choices=blood, null=True)
    image1 = models.ImageField(verbose_name='画像1',null=True)
    last_login = models.DateTimeField(max_length=8,verbose_name='最終ログイン',auto_now=True)
    comment = models.TextField(verbose_name='コメント',null=True)
    egcontact = models.EmailField(verbose_name='緊急連絡先',null=True)

    class Meta:
        db_table = 'User_info'

    #user_idがレコードで識別する文字列
    def __str__(self):
        return self.user

#日記モデル(画像5枚、タイトル、コメント、日付、公開非公開設定、公開用ネーム設定)
class Diary(models.Model):
    IS_USED_CHOICES = (
        (True,'公開'),
        (False, '非公開'),
    )
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(max_length=50,verbose_name='タイトル',null=False)
    comment = models.TextField(verbose_name='コメント',null=True)
    date = models.DateField(default=timezone.now,verbose_name='日付')
    image1 = models.ImageField(verbose_name='画像1', blank=True, null=True)
    image2 = models.ImageField(verbose_name='画像2', blank=True, null=True)
    image3 = models.ImageField(verbose_name='画像3', blank=True, null=True)
    image4 = models.ImageField(verbose_name='画像4', blank=True, null=True)
    image5 = models.ImageField(verbose_name='画像5', blank=True, null=True)
    publicprivate = models.BooleanField(verbose_name='公開非公開', choices=IS_USED_CHOICES,blank=True, null=True)
    publicname = models.CharField(verbose_name='公開用ネーム',max_length=50,blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    class Meta:
        db_table = 'diary_info'

    def __str__(self):
        return self.title

#日記コメント(名前、コメント、日時、対象コメント)
class DiaryComment(models.Model):
    name = models.CharField('名前',max_length=255,default='名無し')
    comment = models.TextField('本文')
    target = models.ForeignKey(Diary, on_delete=models.CASCADE, verbose_name='対象記事',null=True)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.comment[:20]

class Room(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    created_at = models.DateTimeField(default=timezone.now)

class Message(models.Model):
    id = models.AutoField(primary_key=True)
    room = models.ForeignKey(
        Room,
        blank=True,
        null=True,
        related_name='room_meesages',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=20, null=True, blank=True)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

teamG_study/precomi/forms.py
import os
from django import forms
from .models import User, Diary ,DiaryComment
from django.core.mail import EmailMessage

import datetime


#ユーザプロフィールの新規作成(誕生日、性別、電話番号、妊娠周期、血液型、コメント、緊急連絡先)
class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        today = datetime.date.today()
        fields = ('name', 'datebirth','telnum','precycle','bloodtype','comment', 'image1','egcontact')
        widgets = {
            'datebirth': forms.SelectDateWidget(years=[x for x in range(today.year-50, today.year+1)])
        }
        MONTHS = {
            1: 'jan', 2: 'feb', 3: 'mar', 4: 'apr',
            5: 'may', 6: 'jun', 7: 'jul', 8: 'aug',
            9: 'sep', 10: 'oct', 11: 'nov', 12: 'dec'
        }
        forms.SelectDateWidget(months=MONTHS)

    def __int__(self,args,**kwargs):
        super().__init__(*args,**kwargs)
        for fields in self.fields.values():
            fields.widget.attrs['class'] = 'form-control'


class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'teamgtnkma@outlook.jp'
        to_list = [
            'teamgtnkma@outlook.jp'
        ]
        cc_list = [
            email

        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('title', 'comment', 'image1', 'image2', 'image3', 'image4', 'image5','publicprivate','publicname')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'



#コメント投稿フォーム
class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = DiaryComment
        exclude = ('target','created_at')

teamG_study/precomi/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.views import generic
from .forms import UserCreateForm, DiaryCreateForm, InquiryForm ,CommentCreateForm
from  django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from .models import *
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.template import loader
from django.http import HttpResponseRedirect, HttpResponse
from django.views import View
#実験
from django.views.generic.edit import CreateView

import logging
logger = logging.getLogger(__name__)




#index.htmlに飛ばす
class IndexView(generic.TemplateView):
    template_name = "index.html"

#talk.htmlに飛ばす
class TalkView(generic.TemplateView):
    template_name = "talk.html"

#緊急通知の画面に飛ばす
class NoticeView(generic.TemplateView):
    template_name = "notice.html"


# #diary.htmlに飛ばす
class DiaryView(LoginRequiredMixin, generic.ListView):
    model = Diary
    template_name = "diary.html"
    paginate_by = 4

    def get_queryset(self):
        diaries = Diary.objects.filter(user=self.request.user).order_by('-created_at')
        return diaries

#diary詳細
class DiaryDetailView(LoginRequiredMixin, generic.DetailView):
    model = Diary
    template_name = 'diary_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print((self.kwargs['pk']))
        context['comments'] = DiaryComment.objects.filter(target=Diary.objects.get(id=self.kwargs['pk']))
        return context

#diary作成
class DiaryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Diary
    template_name = "diary_create.html"
    form_class = DiaryCreateForm
    success_url = reverse_lazy('precomi:diary')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.user = self.request.user
        diary.save()
        messages.success(self.request, '日記を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "日記の作成に失敗しました。")
        return super().form_invalid(form)

#diary更新
class DiaryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Diary
    template_name = "diary_update.html"
    form_class = DiaryCreateForm

    def get_success_url(self):
        return reverse_lazy('precomi:diary_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, '日記を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "日記の更新に失敗しました。")
        return super().form_invalid(form)

# #diary削除
class DiaryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Diary
    template_name = "diary_delete.html"
    success_url = reverse_lazy('precomi:diary')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "日記を削除しました。")
        return super().delete(request, *args, **kwargs)

#全体表示日記htmlに飛ばす
class AlldiaryView(LoginRequiredMixin,generic.ListView):
    model = Diary
    template_name = "alldiary.html"
    paginate_by = 4


    def get_queryset(self):
        diaries = Diary.objects.all().exclude(user=self.request.user).filter(publicprivate=True).order_by('-created_at')

        return diaries

#コメント投稿ページのビュー
class CommentView(CreateView):
    template_name = 'comment_form.html'
    model = DiaryComment
    form_class = CommentCreateForm
    #success_url = '/'

    #フォームに入力された情報が正しい場合の処理
    def form_valid(self, form):
        post_pk = self.kwargs['pk']
        post = get_object_or_404(Diary,pk=post_pk)
        comment = form.save(commit=False)
        comment.target = post
        comment.save()
        print("ヴァリデーションOK")
        # print("ここまでやってる")
        # return redirect('/')
        return redirect('precomi:diary_detail',pk=post_pk)
    # diary-detail/2/
    def form_invalid(self, form):
        print("ヴァリデーションNG")
        return redirect('/')

    #htmlテンプレートに渡すデータを定義
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post'] = get_object_or_404(Diary,pk=self.kwargs['pk'])
        return context
# #======================================================

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('precomi:inquiry')

    def form_valid(self,form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)


#profile.htmlに飛ばす
class ProfileView(LoginRequiredMixin, generic.ListView):
    model = User
    template_name = "profile.html"

    def get_queryset(self):
        profile = User.objects.filter(user=self.request.user)
        return profile


class ProfileCreateView(LoginRequiredMixin, generic.CreateView):
    model = User
    template_name = 'profile_create.html'
    form_class = UserCreateForm
    success_url = reverse_lazy('precomi:profile')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.user = self.request.user
        user.save()
        messages.success(self.request, '作成しました')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "作成に失敗しました")
        return super().form_invalid(form)
#profile_update.htmlに飛ばす
class ProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = User
    template_name = "profile_update.html"
    form_class = UserCreateForm

    def get_success_url(self):
        return reverse_lazy('precomi:profile')

    def form_valid(self, form):
        messages.success(self.request, 'プロフィールを更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "プロフィールの更新に失敗しました。")
        return super().form_invalid(form)

class ChatIndexView(LoginRequiredMixin, generic.ListView):
    model = Room
    template_name = "chat_index.html"

    def get_context_data(self, **kwargs):
        room_list = Room.objects.order_by('-created_at')[:6]
        room_all = Room.objects.all()
        context = {
            'room_list': room_list,
            'room_all': room_all
        }
        return context

# def chat_index(request):
#     room_list = Room.objects.order_by('-created_at')[:6]
#     room_all = Room.objects.all()
#     template = loader.get_template('chat_index.html')
#     context = {
#         'room_list': room_list,
#         'room_all': room_all
#     }
#     return HttpResponse(template.render(context, request))

def chat_room(request, room_name):
    db_messages = Message.objects.filter(room__name=room_name).order_by('-created_at').reverse()[:50]
    room = Room.objects.filter(name=room_name)[0]
    template = loader.get_template('chat_room.html')
    context = {
        'db_messages': db_messages,
        'room_name': room_name,
    }
    return HttpResponse(template.render(context, request))

def room(request):
    name = request.POST.get("room_name")
    room = Room.objects.create(name=name)
    return HttpResponseRedirect(reverse('precomi:chat_room', args=[name]))

teamG_study/precomi/templates/chat_index.html
{% extends 'base.html' %}
{% load static %}

{% block header%}
{% endblock %}
{% block contents%}
<h2 style="text-align:center">ルーム一覧</h2>
<ul style="text-align:center" class="select-room-box">
    <select id="select-box">
        {% for room in room_all %}
        <a href="/chat_r/{{ room.name }}">
            <option hidden>選択してください</option>
            <option value="{{ room.name }}">{{ room.name }}</option>
        </a>
        {% endfor %}
    </select>
</ul>
<div class="create-room-box" style="text-align:center">
    <form action="/room/" method="post" name="room_form">
        {% csrf_token %}
        部屋を作成しますか？<br>
        {% if error %}
            {{ error }}
        {% endif %}
        <input placeholder="ルームを作成" id="room-name-input" name="room_name" type="text" size="100">
        <input id="room-name-submit" type="submit" class="send" value="作成" onClick="return check();">
    </form>
</div>




{{ room_name|json_script:"room-name" }}
    <script>
        const selectBox = document.getElementById("select-box"); selectBox.addEventListener("change", function() {
        const selectedValue = selectBox.value;
        window.location.href = "/chat_r/" + selectedValue;
        });

        <!--同じ名前のルームを作らせない-->
        function check(){
                let num = 0;
                {% for room in room_all %}
                if (room_form.room_name.value == "{{ room.name }}"){
                    alert("このルーム名は既に存在します");
                    return false;
                } else if (room_form.room_name.value == ""){
                    alert("入力してください");
                    return false;
                }else{
                    num = 1;
                }
                {% endfor %}
                if (num == 1){
                    return true;
                } else{
                    return false;
                }
        }
    </script>

{% endblock %}

teamG_study/precomi/templates/comment_form.html
{% extends 'base.html' %}
{% load static %}


{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container col-lg-6 offset-lg-3">
    <!---記事タイトルを表示-->
    <h4 class="titleline">
        <div class="col-3">
            タイトル:{{ post.title }}
        </div>
    </h4>
    <form action="" method="POST" id="comment-form">
          {% csrf_token %}
          <table class="table">
                {{ form.as_table }}
          </table>
        <div class="row my-3">
            <button type="submit" class="btn btn-success col-3 offset-2">投稿する</button>
            <a class="btn btn-danger col-3 offset-2" href="{% url 'precomi:diary_detail' post.pk %}">キャンセル</a>
        </div>
    </form>
</div>
{% endblock %}

teamG_study/precomi/templates/comment_list.html
{% extends 'base.html' %}
{% load static %}
}

{% block active_diary_list %}active{% endblock %}


{% block contents %}
<h3 class="comment-title">コメント</h3>
<!--コメント-->

{% for comment in comment_list %}
<div class="comment-list">
    <div class='border-bottom'>{{ comment.user_name }}　{{ comment.created_at }}</div>
    <!--改行しないようlinebreaksを設定,URL要素に<a>要素を設定-->
    <div class='mt-2'>{{ comment.message | linebreaks | urlize }}</div>
</div>
{% empty %}
<p>コメントはありません</p>
{% endfor %}
{% endblock %}

teamG_study/precomi/templates/diary.html
{% extends 'base.html' %}
{% load static %}


{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="{% url 'precomi:diary_create' %}">新規作成</a>
                </div>
                {% for diary in diary_list %}
                    <div class="post-preview">
                        <a href="{% url 'precomi:diary_detail' diary.pk %}" style="text-decoration: none;">
                          <h2 class="post-title">
                            {{ diary.title }}
                          </h2>
                          <div style="text-align:right">
                            {% if diary.image1 %}
                                <img src="{{ diary.image1.url }}" class="thumbnail">
                            {% elif diary.image2 %}
                                <img src="{{ diary.image2.url }}" class="thumbnail">
                            {% elif diary.image3 %}
                                <img src="{{ diary.image3.url }}" class="thumbnail">
                            {% elif diary.image4 %}
                                <img src="{{ diary.image4.url }}" class="thumbnail">
                            {% elif diary.image5 %}
                                <img src="{{ diary.image5.url }}" class="thumbnail">
                            {% endif %}
                          </div>
                        </a>
                        <p >
                            {% if diary.publicprivate == True %}
                                公開
                            {% elif diary.publicprivate == False %}
                                非公開
                            {% endif %}
                        </p>
                        <p class="post-meta">{{ diary.created_at }}</p>
                    </div>
                    <hr>
                {% empty %}
                    <p>日記がありません。</p>
                {% endfor %}

                <!-- ページネーション処理 -->
                {% if is_paginated %}
                    <ul class="pagination">
                        <!-- 前ページへのリンク -->
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        <!-- ページ数表示 -->
                        {% for page_num in page_obj.paginator.page_range %}
                            {% if page_obj.number == page_num %}
                                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <!-- 次ページへのリンク -->
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

teamG_study/precomi/templates/diary_create.html
{% extends 'base.html' %}
{% load static %}


{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
                <a class="btn btn-secondary ml-2" href="{% url 'precomi:diary' %}">戻る</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

teamG_study/precomi/templates/diary_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記削除 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST">
                {% csrf_token %}
                <p>本当に削除しますか？</p>
                <button class="btn btn-primary mt-5" type="submit">削除</button>
                <a class="btn btn-secondary mt-5 ml-2" href="{% url 'precomi:diary_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

teamG_study/precomi/templates/diary_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記編集 | Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">更新</button>
                <a class="btn btn-secondary ml-2" href="{% url 'precomi:diary_detail' object.pk %}">戻る</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

teamG_study/precomi/templates/edit.html
{% extends 'base.html' %}
{% load static %}
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>プロフィール編集</title>
    <meta name="description" content="プロフィール編集">
</head>
{% block contents%}
<body>
    <div>
        <button type="button"><a href="{% url 'precomi:profile' %}">完了</a></button>
    </div>
    <div>
        <form action="test.html" method="post" enctype="multipart/form-data" >
    <div>
        <input type="file" name="test" multiple/>
    </div>
        </form>
    </div>
    <div>
        <form  action="">
            ファイルを選択
            <input id="filename" readonly type="text" value="" ><button type="button" id="select_file_button">選択</button>
            <input id="file_button" type="file"  />
            <input type="submit" name="commit" value="プロフィール編集を完了する" /></div>
        </form>
    </div>
    <p>
        週　日　妊娠　か月
        名前：
        出産予定日
        ・生年月日：
        ・年齢：
        ・月経周期：
        ・出産予定日：
        ・血液型：
        ・緊急連絡先：
        コメント欄
    </p>
</body>
</html>
{% endblock %}

teamG_study/precomi/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block header%}
{% endblock %}
<!--メイン画像 赤ちゃん-->
{% block contents%}
<div id="main visual" class="container imgcenter">
  <img id="circle" class="mainimg" src="{% static 'images/01.jpg' %}">
</div>
{% endblock %}

teamG_study/precomi/templates/inquiry.html
{% extends 'base.html' %}

{% block active_inquiry %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="post">
                {% csrf_token %}

                {{ form.non_field_errors }}

                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                            {{ field.errors }}
                        </div>
                    </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

teamG_study/precomi/templates/notice.html
{% extends 'base.html' %}
{% load static %}
{% block contents%}
<div id="main visual">
  <a href="tel:"><img id="circle" src="{% static 'images/w.png' %}"></a>
</div>
<body>

</body>
{% endblock %}

teamG_study/precomi/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block contents %}

    {% if not user_list %}
        <div>
            <a class="btn btn-primary float-right" href="{% url 'precomi:profile_create' %}">新規</a>
        </div>
    {% endif %}
    {% for i in user_list %}
        <div style="text-align:center">
            {% if i.image1 %}
                <img src="{{ i.image1.url }}" class="pimg" width="200" height="200"></img>
            {% else %}
            {% endif %}
        </div>
        <div class="flex between imgcenter"  style="text-align:center" id="prof_id">
            <h2 class="item prof_data">
                名前<br>
                {{ i.name }}
            </h2>
            <h2 class="item prof_data">
                生年月日<br>
                {{i.datebirth}}
            </h2>
            <h2 class="item prof_data">
                血液型<br>
                {{i.bloodtype}}
            </h2>
            <h2 class="item prof_data">
                月経周期<br>
                {{i.precycle}}
            </h2>
            <h2 class="item prof_data">
                電話番号<br>
                {{i.telnum}}
            </h2>
            <h2 class="item prof_data">
                緊急連絡先<br>
                {{i.egcontact}}
            </h2>
            <h2 class="item prof_data">
                コメント<br>
                {{i.comment| linebreaksbr }}
            </h2>
        </div>
        <div style="text-align:right">
            <a href="{% url 'precomi:profile_update' i.pk %}" class="btn btn-primary">編集</a>
        </div>
    {% empty %}
        <p>プロフィールがありません。</p>
    {% endfor %}
{% endblock %}